steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/h2ox-api', '-f', './Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/h2ox-api']
images:
  - 'gcr.io/$PROJECT_ID/h2ox-api'